name: "Compare and Deploy"
description: ""
inputs:
  source:
    description: "Source folder (already built)"
    required: true
  source-key:
    description: "Source cache key to restore from"
    required: false
    default: 'false'
  target:
    description: "Target folder (already built)"
    required: true
  target-key:
    description: "Target cache key to restore from"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Path Setup
      shell: bash
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: Cache Target
      if: ${{ inputs.source-key != 'false' }}
      uses: actions/cache@v3
      with:
        path: "${{ inputs.source }}"
        key: ${{ inputs.source-key }}

    - name: Cache Target
      if: ${{ inputs.target-key != 'false' }}
      uses: actions/cache@v3
      with:
        path: "${{ inputs.target }}"
        key: ${{ inputs.target-key }}

    - name: Source
      shell: bash
      run: ls -al "${{ inputs.source }}";

    - name: Target
      shell: bash
      run: ls -al "${{ inputs.target }}";
