name: "Compare and Deploy"
description: ""
inputs:
  source:
    description: "Source folder (already built)"
    required: true
  target:
    description: "Target folder (already built)"
    required: true
runs:
  using: "composite"
  steps:
    - name: Path Setup
      shell: bash
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: Cache Key
      id: cache-key
      shell: bash
      run: |
        cache_hash() {
          local PREFIX;
          PREFIX=${2};
          if [ -n "${PREFIX}" ]; then
            PREFIX="${PREFIX}-"
          fi
          echo -n "${1}" | md5sum | awk -v prefix="${PREFIX}" '{print prefix$1}'
        }
        KEY=$(cache_hash "${{ inputs.path }}" "${{ github.run_number }}")
        echo "::set-output name=key::${KEY}"; # set up cache action with this key on the path

    - name: Cache
      uses: actions/cache@v3
      with:
        path: "${{ inputs.path }}"
        key: ${{ steps.cache-key.outputs.key }}

    - name: Source
      shell: bash
      run: echo "${{ inputs.source }}";

    - name: Target
      shell: bash
      run: echo "${{ inputs.target }}";
