name: Build & Deploy
on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2 # Wont be needed when actions are public

      - run: cd ./.github/actions/persistent && npm ci # Wont be needed when actions are public

      - uses: ./.github/actions/persistent
        id: get-ref
        with:
          get: last_ref

      - name: Checkout Source
        uses: ./.github/actions/checkout-extended
        with:
          path: "source"
          use: "${{ steps.get-ref.outputs.value }}"

      - name: Build Source
        uses: ./.github/actions/build
        with:
          path: "source"

      - name: Checkout Target
        uses: ./.github/actions/checkout-extended
        with:
          path: "target"

      - name: Build Target
        uses: ./.github/actions/build
        with:
          path: "target"

      - name: Deploy
        uses: ./.github/actions/deploy-ftp
        with:
          source: "source"
          target: "target"
          env-type: "sftp"
          env-host: ${{ secrets.ENV_HOST }}
          env-port: ${{ secrets.ENV_PORT }}
          env-user: ${{ secrets.ENV_USER }}
          env-pass: ${{ secrets.ENV_PASS }}
          env-remote-root: ${{ secrets.ENV_REMOTE_ROOT }}

      - name: Set last_ref on the persistent env
        uses: ./.github/actions/persistent
        with:
          set: last_ref
          value: ${{ github.sha }}
