name: Build & Deploy
on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build-source:
    name: Build Source
    runs-on: ubuntu-latest
    outputs:
      commit-sha: ${{ steps.build.outputs.commit-sha }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2 # Wont be needed when actions are public

      - run: cd ./.github/actions/persistent && npm ci # Wont be needed when actions are public

      - name: SharedFS
        uses: ./.github/actions/sharefs
        with:
          path: "source"

      - uses: ./.github/actions/persistent
        id: get-ref
        with:
          get: last_ref

      - name: Checkout Source
        uses: ./.github/actions/checkout-extended
        with:
          path: "source"
          use: "${{ steps.get-ref.outputs.value }}"

      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          path: "source"
  build-target:
    name: Build Target
    runs-on: ubuntu-latest
    outputs:
      commit-sha: ${{ steps.build.outputs.commit-sha }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2 # Wont be needed when actions are public

      - name: SharedFS
        uses: ./.github/actions/sharefs
        with:
          path: "target"

      - name: Checkout Source
        uses: ./.github/actions/checkout-extended
        with:
          path: "target"

      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          path: "target"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-source, build-target]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2 # Wont be needed when actions are public

      - run: cd ./.github/actions/persistent && npm ci # Wont be needed when actions are public

      - name: SharedFS
        uses: ./.github/actions/sharefs
        with:
          path: "source"

      - name: SharedFS
        uses: ./.github/actions/sharefs
        with:
          path: "target"

      - name: Deploy
        uses: ./.github/actions/deploy-ftp
        with:
          env-type: 'sftp'
          env-host: ${{ secrets.ENV_HOST }}
          env-port: ${{ secrets.ENV_PORT }}
          env-user: ${{ secrets.ENV_USER }}
          env-pass: ${{ secrets.ENV_PASS }}
          env-remote-root: ${{ secrets.ENV_REMOTE_ROOT }}

      - name: Set last_ref on the persistent env
        uses: ./.github/actions/persistent
        with:
          set: last_ref
          value: ${{ github.sha }}
