name: Build & Deploy
on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build-source:
    name: Build Source
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.build.outputs.cache-key }}
      commit-sha: ${{ steps.build.outputs.commit-sha }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2 # Wont be needed when actions are public

      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          path: "source"
          use: "last"
  build-target:
    name: Build Target
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.build.outputs.cache-key }}
      commit-sha: ${{ steps.build.outputs.commit-sha }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2 # Wont be needed when actions are public

      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          path: "target"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-source, build-target]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2 # Wont be needed when actions are public

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          source: "source"
          source-key: "${{needs.build-source.outputs.cache-key}}"
          target: "target"
          target-key: "${{needs.build-target.outputs.cache-key}}"
          env-type: 'sftp'
          env-host: ${{ secrets.ENV_HOST }}
          env-port: ${{ secrets.ENV_PORT }}
          env-user: ${{ secrets.ENV_USER }}
          env-pass: ${{ secrets.ENV_PASS }}
          env-remote-root: ${{ secrets.ENV_REMOTE_ROOT }}
